server:
  port: 8080
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 8192
    accept-count: 100
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    path: /error

spring:
  application:
    name: alfa
  devtools:
    livereload:
      enabled: true
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
#    username: sa
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${AWS_RDS_ENDPOINT}:3306/${AWS_RDS_DATABASE}
    username: ${AWS_RDS_USERNAME}
    password: ${AWS_RDS_PASSWORD}
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        default_batch_fetch_size: 1000
#        globally_quoted_identifiers: true
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
    open-in-view: false
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 2000
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 1MB
      max-request-size: 10MB
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
#  mail:
#    host: localhost
#    port: 25
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_GOOGLE_USERNAME}
    password: ${SMTP_GOOGLE_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

#AWS configuration
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false

#SpringDoc OpenAPI UI configuration
springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true

#logging:
#  level:
#    org.hibernate.sql: debug
#    org.hibernate.type: trace

#Spring Boot DataSource Decorator configuration
decorator:
  datasource:
    p6spy:
      logging: slf4j
      enable-logging: true
      multiline: true

#General configuration
app:
  frontend:
    url: ${FRONTEND_URL}
#file:
#  upload:
#    location: ${LOCAL_FILE_UPLOAD_LOCATION}

#JWT configuration
jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  token:
    access-expiration: 1800
    refresh-expiration: 604800

#Email configuration
email:
  from: no-reply@${FRONTEND_URL}

#AWS S3 configuration
aws:
  s3:
    bucket: ${AWS_S3_BUCKET}
    upload-dir: ${AWS_S3_UPLOAD_DIR}

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  mail:
    host: localhost
    port: 3025
    username: springboot
    password: secret
    properties:
      mail:
        smtp:
          starttls:
            enable: false
            required: false

#AWS configuration
cloud:
  aws:
    credentials:
      access-key: ""
      secret-key: ""
    region:
      static: ""

#General configuration
app:
  frontend:
    url: ""
file:
  upload:
    location: Z:/

#JWT configuration
jwt:
  secret: SECRET
  issuer: ISSUER

#Email configuration
email:
  from: no-reply@mail.com

#AWS S3 configuration
aws:
  s3:
    bucket: ""
    upload-dir: ""